version: '3'
services:
  # MySQL service
  mysql:
    image: mysql:latest
    container_name: ralali-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ralali
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql

  # Golang app service
  golang-app:
    build:
      dockerfile: Dockerfile
    container_name: ralali-echo
    restart: always
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: root
      DB_NAME: ralali
      PORT: 8080
    ports:
      - "8080:8080"

volumes:
  mysql-data:
